"""
Django settings for noctis_pro project.

Generated by 'Django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Import workspace auto-detection
try:
    from .workspace_detector import get_workspace_config, get_django_settings
    # Get workspace configuration
    WORKSPACE_CONFIG = get_workspace_config()
    DJANGO_WORKSPACE_SETTINGS = get_django_settings()
    
    # Print detection report if in debug mode or if explicitly requested
    if os.getenv('SHOW_WORKSPACE_REPORT', '').lower() in ('1', 'true', 'yes'):
        from .workspace_detector import print_workspace_report
        print_workspace_report()
        
except ImportError as e:
    # Fallback if workspace detector is not available
    print(f"Warning: Workspace auto-detection not available: {e}")
    WORKSPACE_CONFIG = {
        'workspace_type': 'fallback',
        'base_path': BASE_DIR,
        'is_development': True,
        'debug': True,
    }
    DJANGO_WORKSPACE_SETTINGS = {
        'DEBUG': True,
        'ALLOWED_HOSTS': ['localhost', '127.0.0.1'],
        'DATABASE_URL': None,
        'REDIS_URL': 'redis://localhost:6379/0',
        'LOG_LEVEL': 'DEBUG',
    }


def get_env_bool(env_var_name: str, default: bool = False) -> bool:
    """Parse a boolean environment variable with sensible defaults."""
    return os.getenv(env_var_name, str(default)).lower() in ("1", "true", "yes", "on")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use workspace auto-detection to determine DEBUG mode, with env override
DEBUG = get_env_bool('DEBUG', DJANGO_WORKSPACE_SETTINGS.get('DEBUG', True))
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG or WORKSPACE_CONFIG.get('is_development', True):
        SECRET_KEY = 'dev-insecure-secret-key-auto-detected'
    else:
        raise ValueError('SECRET_KEY environment variable must be set in production')

# SECURITY WARNING: do not use wildcard hosts in production
# Use workspace auto-detection for allowed hosts, with env override
env_allowed_hosts = os.getenv('ALLOWED_HOSTS')
if env_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in env_allowed_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = DJANGO_WORKSPACE_SETTINGS.get('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    
    # Custom apps
    'accounts',
    'worklist',
    'dicom_viewer',
    'reports',
    'admin_panel',
    'chat',  # Re-enabled to fix template URLs
    'notifications',  # Re-enabled to fix User.notifications relationship
    'ai_analysis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noctis_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'noctis_pro.wsgi.application'
ASGI_APPLICATION = 'noctis_pro.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use workspace auto-detection for database configuration
DATABASE_URL = os.getenv('DATABASE_URL') or DJANGO_WORKSPACE_SETTINGS.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv('CONN_MAX_AGE', '60')),
            ssl_require=get_env_bool('DB_SSL_REQUIRE', False),
        )
    }
else:
    # Development fallback to SQLite when DATABASE_URL is not provided
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Redis configuration for channels - use workspace auto-detection
REDIS_URL = os.getenv('REDIS_URL') or DJANGO_WORKSPACE_SETTINGS.get('REDIS_URL', 'redis://localhost:6379/0')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Use workspace auto-detection for static root
STATIC_ROOT = os.getenv('STATIC_ROOT') or DJANGO_WORKSPACE_SETTINGS.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploads) - use workspace auto-detection
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT') or DJANGO_WORKSPACE_SETTINGS.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# DICOM files storage
DICOM_ROOT = os.path.join(MEDIA_ROOT, 'dicom')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',') if origin.strip()
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000').split(',') if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/worklist/'
LOGOUT_REDIRECT_URL = '/login/'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# SSL/Proxy settings for HTTPS behind Caddy - use workspace auto-detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = get_env_bool('SECURE_SSL_REDIRECT', 
                                  DJANGO_WORKSPACE_SETTINGS.get('SECURE_SSL_REDIRECT', not DEBUG))

# Cookies and transport security - use workspace auto-detection
SESSION_COOKIE_SECURE = get_env_bool('SESSION_COOKIE_SECURE', 
                                    DJANGO_WORKSPACE_SETTINGS.get('SESSION_COOKIE_SECURE', not DEBUG))
CSRF_COOKIE_SECURE = get_env_bool('CSRF_COOKIE_SECURE', 
                                 DJANGO_WORKSPACE_SETTINGS.get('CSRF_COOKIE_SECURE', not DEBUG))
# Parse SECURE_HSTS_SECONDS with error handling
try:
    hsts_value = os.getenv('SECURE_HSTS_SECONDS', '0').strip()
    # Handle case where environment variables might be malformed/concatenated
    if not hsts_value.isdigit():
        print(f"Warning: SECURE_HSTS_SECONDS value '{hsts_value}' is not a valid integer, using default 0")
        hsts_value = '0'
    SECURE_HSTS_SECONDS = int(hsts_value)
except ValueError as e:
    print(f"Error parsing SECURE_HSTS_SECONDS: {e}")
    print(f"Raw value: '{os.getenv('SECURE_HSTS_SECONDS', '0')}'")
    SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = get_env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'same-origin')

# Logging to stdout/stderr for containerized environments
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL') or DJANGO_WORKSPACE_SETTINGS.get('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'noctis_pro': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
